version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/static_reviewer
    environment:
      TZ: Asia/Tokyo
      FLASK_ENV: development
    command: flask run --host 0.0.0.0 --port 5000
